/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fengyun_diff_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d9fc2140500baed1e956f4682d29479d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <hrpt/fengyun_diff_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <fengyun_diff_decoder_pydoc.h>

void bind_fengyun_diff_decoder(py::module& m)
{

    using fengyun_diff_decoder    = gr::hrpt::fengyun_diff_decoder;


    py::class_<fengyun_diff_decoder,
        std::shared_ptr<fengyun_diff_decoder>>(m, "fengyun_diff_decoder", D(fengyun_diff_decoder))

        .def(py::init(&fengyun_diff_decoder::make),
           D(fengyun_diff_decoder,make)
        )
        



        ;




}








