/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(metop_cadu_deframer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(47961411782b89f033514a2af96792d8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <hrpt/metop_cadu_deframer.h>
// pydoc.h is automatically generated in the build directory
#include <metop_cadu_deframer_pydoc.h>

void bind_metop_cadu_deframer(py::module& m)
{

    using metop_cadu_deframer    = gr::hrpt::metop_cadu_deframer;


    py::class_<metop_cadu_deframer,
        std::shared_ptr<metop_cadu_deframer>>(m, "metop_cadu_deframer", D(metop_cadu_deframer))

        .def(py::init(&metop_cadu_deframer::make),
           py::arg("sync_check"),
           py::arg("frame_length"),
           py::arg("insync_after"),
           py::arg("outsync_after"),
           D(metop_cadu_deframer,make)
        )
        



        ;




}








