/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(noaa_hrpt_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(388d99752fd50f98076a12ad355c83bd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <hrpt/noaa_hrpt_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <noaa_hrpt_decoder_pydoc.h>

void bind_noaa_hrpt_decoder(py::module& m)
{

    using noaa_decoder    = gr::hrpt::noaa_hrpt_decoder;


    py::class_<noaa_decoder,
        std::shared_ptr<noaa_decoder>>(m, "noaa_decoder", D(noaa_decoder))

        .def(py::init(&noaa_decoder::make),
           py::arg("verbose"),
           py::arg("output_files"),
           D(noaa_decoder,make)
        )
        



        ;




}








