/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(viterbi_fengyun_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6762e0efc9329ac0c18cb02800c5dd70)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <hrpt/viterbi_fengyun_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <viterbi_fengyun_decoder_pydoc.h>

void bind_viterbi_fengyun_decoder(py::module& m)
{

    using viterbi_fengyun_decoder    = gr::hrpt::viterbi_fengyun_decoder;


    py::class_<viterbi_fengyun_decoder,
        std::shared_ptr<viterbi_fengyun_decoder>>(m, "viterbi_fengyun_decoder", D(viterbi_fengyun_decoder))

        .def(py::init(&viterbi_fengyun_decoder::make),
           py::arg("sync_check"),
           py::arg("ber_threshold"),
           py::arg("insync_after"),
           py::arg("outsync_after"),
           py::arg("reset_after"),
           D(viterbi_fengyun_decoder,make)
        )
        



        ;




}








